name: ci-sonarqube-android
on:
  pull_request:
    branches: [develop, release]
jobs:
  SonarCloud:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17' 
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Permisos
        run: chmod +x gradlew
      #- name: Build and analyze
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #  run: ./gradlew build sonar --info

      #- name: Build and lint
      #  run: |
      #    ./gradlew build
      #    ./gradlew lintDebug

      - name: Create text file
        run: echo "holajeremy1223" > holajeremy.txt

      - name: Read lint report content
        run: |
          echo "LINT_REPORT_CONTENT=$(cat holajeremy.txt)" >> $GITHUB_ENV

      #- name: Upload lint report
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: lint-report
      #    path: app/build/reports

      - run: env

      - uses: actions/github-script@v7
        with:
          script: |
            const lint_report = process.env.LINT_REPORT_CONTENT;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Lint report content: First Name: ${lint_report}`
            })


